- name: Configure sysctl parameters
  ansible.posix.sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: true
  loop:
    - name: net.ipv4.ip_forward
      value: '{{net_ipv4_ip_forward}}'  # Enable IP forwarding
    - name: net.ipv6.conf.all.disable_ipv6
      value: '{{net_ipv6_conf_all_disable_ipv6}}'  # Disable IPv6 for all network interfaces
    - name: net.ipv6.conf.default.disable_ipv6
      value: '{{net_ipv6_conf_default_disable_ipv6}}'  # Disable IPv6 for the default network interface
    - name: net.ipv4.ip_local_port_range
      value: '{{net_ipv4_ip_local_port_range}}'  # Set the range of local ports for outgoing connections
    - name: net.core.default_qdisc
      value: '{{net_core_default_qdisc}}'  # Set the default queuing discipline to Fair Queueing
    - name: net.ipv4.tcp_congestion_control
      value: '{{net_ipv4_tcp_congestion_control}}'  # Set TCP congestion control algorithm to BBR
    - name: fs.file-max
      value: '{{fs_file_max}}'  # Set the maximum number of file handles
    - name: net.core.rmem_max
      value: '{{net_core_rmem_max}}'  # Set the maximum receive socket buffer size
    - name: net.core.wmem_max
      value: '{{net_core_wmem_max}}'  # Set the maximum send socket buffer size
    - name: net.ipv4.tcp_window_scaling
      value: '{{net_ipv4_tcp_window_scaling}}'  # Enable TCP window scaling
    - name: net.ipv4.tcp_rmem
      value: '{{net_ipv4_tcp_rmem}}'  # Set TCP receive buffer sizes
    - name: net.ipv4.tcp_wmem
      value: '{{net_ipv4_tcp_wmem}}'  # Set TCP send buffer sizes
    - name: net.ipv4.tcp_sack
      value: '{{net_ipv4_tcp_sack}}'  # Enable TCP Selective Acknowledgment (SACK)
    - name: net.ipv4.tcp_timestamps
      value: '{{net_ipv4_tcp_timestamps}}'  # Enable TCP timestamps
    - name: net.ipv4.tcp_max_tw_buckets
      value: '{{net_ipv4_tcp_max_tw_buckets}}'  # Set the maximum number of TCP Time-Wait buckets
    - name: net.ipv4.tcp_mem
      value: '{{net_ipv4_tcp_mem}}'  # Set TCP memory thresholds
    - name: net.core.rmem_default
      value: '{{net_core_rmem_default}}'  # Set the default receive socket buffer size
    - name: net.core.wmem_default
      value: '{{net_core_wmem_default}}'  # Set the default send socket buffer size
    - name: net.ipv4.tcp_fastopen
      value: '{{net_ipv4_tcp_fastopen}}'  # Enable TCP Fast Open
    - name: net.core.somaxconn
      value: '{{net_core_somaxconn}}'  # Set the maximum number of pending connections
    - name: net.ipv4.tcp_max_syn_backlog
      value: '{{net_ipv4_tcp_max_syn_backlog}}'  # Set the maximum number of pending TCP SYN requests
    - name: net.core.netdev_max_backlog
      value: '{{net_core_netdev_max_backlog}}'  # Set the maximum number of queued packets on network interfaces